<a href="https://colab.research.google.com/github/GovindSingh9447/.github/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
b=np.array([[1,2,3,4,5],[0,9,8,7,6]])
print(b)
print(type(b))

[[1 2 3 4 5]
 [0 9 8 7 6]]
<class 'numpy.ndarray'>


In [12]:
c=np.array([[[1,2,3,4],[4,3,2,1]],[[1,2,3,4],[4,3,2,1]]])
print(c)

[[[1 2 3 4]
  [4 3 2 1]]

 [[1 2 3 4]
  [4 3 2 1]]]


In [13]:
np.random.randint(2,10,5)

array([3, 9, 9, 2, 7])

In [15]:
np.random.randint(20,size=(4,4))

array([[ 0,  1,  9,  0],
       [ 1,  3, 11,  3],
       [ 5, 14, 14, 11],
       [ 6, 10, 10,  6]])

In [16]:
np.array([1,2,3,4,5],dtype=bool)

array([ True,  True,  True,  True,  True])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [23]:
from numpy import *
a= arange(12)
a=a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
